_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 2");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 2:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 2:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 2:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 3");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 3:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 3:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 4");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 4:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 5");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 5:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 5:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 6");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 6:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 6:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 7");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 7:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 7:ret");
_Static_assert(sizeof(struct unixcall_nsstring_getcstring) == 40, "ABI size 8");
_Static_assert(offsetof(struct unixcall_nsstring_getcstring, str) == 0 && sizeof(((struct unixcall_nsstring_getcstring *)0)->str) == 8, "ABI field 8:str");
_Static_assert(offsetof(struct unixcall_nsstring_getcstring, buffer_ptr) == 8 && sizeof(((struct unixcall_nsstring_getcstring *)0)->buffer_ptr) == 8, "ABI field 8:buffer_ptr");
_Static_assert(offsetof(struct unixcall_nsstring_getcstring, max_length) == 16 && sizeof(((struct unixcall_nsstring_getcstring *)0)->max_length) == 8, "ABI field 8:max_length");
_Static_assert(offsetof(struct unixcall_nsstring_getcstring, encoding) == 24 && sizeof(((struct unixcall_nsstring_getcstring *)0)->encoding) == 8, "ABI field 8:encoding");
_Static_assert(offsetof(struct unixcall_nsstring_getcstring, ret) == 32 && sizeof(((struct unixcall_nsstring_getcstring *)0)->ret) == 4, "ABI field 8:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 9");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 9:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 9:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 9:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 10");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 10:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 11");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 11:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 11:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 12");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 12:handle");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 13");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 13:handle");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 14");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 14:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 14:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 15");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 15:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 15:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 16");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 16:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 16:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_uint64_noret) == 24, "ABI size 17");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->handle) == 8, "ABI field 17:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, arg0) == 8 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->arg0) == 8, "ABI field 17:arg0");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, arg1) == 16 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->arg1) == 8, "ABI field 17:arg1");
_Static_assert(sizeof(struct unixcall_mtldevice_newbuffer) == 24, "ABI size 18");
_Static_assert(offsetof(struct unixcall_mtldevice_newbuffer, device) == 0 && sizeof(((struct unixcall_mtldevice_newbuffer *)0)->device) == 8, "ABI field 18:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newbuffer, info) == 8 && sizeof(((struct unixcall_mtldevice_newbuffer *)0)->info) == 8, "ABI field 18:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newbuffer, ret) == 16 && sizeof(((struct unixcall_mtldevice_newbuffer *)0)->ret) == 8, "ABI field 18:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newsamplerstate) == 24, "ABI size 19");
_Static_assert(offsetof(struct unixcall_mtldevice_newsamplerstate, device) == 0 && sizeof(((struct unixcall_mtldevice_newsamplerstate *)0)->device) == 8, "ABI field 19:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newsamplerstate, info) == 8 && sizeof(((struct unixcall_mtldevice_newsamplerstate *)0)->info) == 8, "ABI field 19:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newsamplerstate, ret) == 16 && sizeof(((struct unixcall_mtldevice_newsamplerstate *)0)->ret) == 8, "ABI field 19:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newdepthstencilstate) == 24, "ABI size 20");
_Static_assert(offsetof(struct unixcall_mtldevice_newdepthstencilstate, device) == 0 && sizeof(((struct unixcall_mtldevice_newdepthstencilstate *)0)->device) == 8, "ABI field 20:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newdepthstencilstate, info) == 8 && sizeof(((struct unixcall_mtldevice_newdepthstencilstate *)0)->info) == 8, "ABI field 20:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newdepthstencilstate, ret) == 16 && sizeof(((struct unixcall_mtldevice_newdepthstencilstate *)0)->ret) == 8, "ABI field 20:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newtexture) == 24, "ABI size 21");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, device) == 0 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->device) == 8, "ABI field 21:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, info) == 8 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->info) == 8, "ABI field 21:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, ret) == 16 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->ret) == 8, "ABI field 21:ret");
_Static_assert(sizeof(struct unixcall_mtlbuffer_newtexture) == 40, "ABI size 22");
_Static_assert(offsetof(struct unixcall_mtlbuffer_newtexture, buffer) == 0 && sizeof(((struct unixcall_mtlbuffer_newtexture *)0)->buffer) == 8, "ABI field 22:buffer");
_Static_assert(offsetof(struct unixcall_mtlbuffer_newtexture, info) == 8 && sizeof(((struct unixcall_mtlbuffer_newtexture *)0)->info) == 8, "ABI field 22:info");
_Static_assert(offsetof(struct unixcall_mtlbuffer_newtexture, offset) == 16 && sizeof(((struct unixcall_mtlbuffer_newtexture *)0)->offset) == 8, "ABI field 22:offset");
_Static_assert(offsetof(struct unixcall_mtlbuffer_newtexture, bytes_per_row) == 24 && sizeof(((struct unixcall_mtlbuffer_newtexture *)0)->bytes_per_row) == 8, "ABI field 22:bytes_per_row");
_Static_assert(offsetof(struct unixcall_mtlbuffer_newtexture, ret) == 32 && sizeof(((struct unixcall_mtlbuffer_newtexture *)0)->ret) == 8, "ABI field 22:ret");
_Static_assert(sizeof(struct unixcall_mtltexture_newtextureview) == 48, "ABI size 23");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, texture) == 0 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->texture) == 8, "ABI field 23:texture");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, format) == 8 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->format) == 4, "ABI field 23:format");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, texture_type) == 12 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->texture_type) == 4, "ABI field 23:texture_type");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, level_start) == 16 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->level_start) == 2, "ABI field 23:level_start");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, level_count) == 18 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->level_count) == 2, "ABI field 23:level_count");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, slice_start) == 20 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->slice_start) == 2, "ABI field 23:slice_start");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, slice_count) == 22 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->slice_count) == 2, "ABI field 23:slice_count");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, swizzle) == 24 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->swizzle) == 4, "ABI field 23:swizzle");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, ret) == 32 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->ret) == 8, "ABI field 23:ret");
_Static_assert(offsetof(struct unixcall_mtltexture_newtextureview, gpu_resource_id) == 40 && sizeof(((struct unixcall_mtltexture_newtextureview *)0)->gpu_resource_id) == 8, "ABI field 23:gpu_resource_id");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 24");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 24:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 24:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 24:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newlibrary) == 32, "ABI size 25");
_Static_assert(offsetof(struct unixcall_mtldevice_newlibrary, device) == 0 && sizeof(((struct unixcall_mtldevice_newlibrary *)0)->device) == 8, "ABI field 25:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newlibrary, data) == 8 && sizeof(((struct unixcall_mtldevice_newlibrary *)0)->data) == 8, "ABI field 25:data");
_Static_assert(offsetof(struct unixcall_mtldevice_newlibrary, ret_error) == 16 && sizeof(((struct unixcall_mtldevice_newlibrary *)0)->ret_error) == 8, "ABI field 25:ret_error");
_Static_assert(offsetof(struct unixcall_mtldevice_newlibrary, ret_library) == 24 && sizeof(((struct unixcall_mtldevice_newlibrary *)0)->ret_library) == 8, "ABI field 25:ret_library");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 26");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 26:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 26:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 26:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 27");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 27:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 27:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 27:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 28");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 28:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 28:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newcomputepso) == 32, "ABI size 29");
_Static_assert(offsetof(struct unixcall_mtldevice_newcomputepso, device) == 0 && sizeof(((struct unixcall_mtldevice_newcomputepso *)0)->device) == 8, "ABI field 29:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newcomputepso, info) == 8 && sizeof(((struct unixcall_mtldevice_newcomputepso *)0)->info) == 8, "ABI field 29:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newcomputepso, ret_error) == 16 && sizeof(((struct unixcall_mtldevice_newcomputepso *)0)->ret_error) == 8, "ABI field 29:ret_error");
_Static_assert(offsetof(struct unixcall_mtldevice_newcomputepso, ret_pso) == 24 && sizeof(((struct unixcall_mtldevice_newcomputepso *)0)->ret_pso) == 8, "ABI field 29:ret_pso");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 30");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 30:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 30:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 31");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 31:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 31:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 31:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 32");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 32:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 32:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 32:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 33");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 33:handle");
_Static_assert(sizeof(struct unixcall_mtldevice_newrenderpso) == 32, "ABI size 34");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, device) == 0 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->device) == 8, "ABI field 34:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, info) == 8 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->info) == 8, "ABI field 34:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, ret_error) == 16 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->ret_error) == 8, "ABI field 34:ret_error");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, ret_pso) == 24 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->ret_pso) == 8, "ABI field 34:ret_pso");
_Static_assert(sizeof(struct unixcall_mtldevice_newmeshrenderpso) == 32, "ABI size 35");
_Static_assert(offsetof(struct unixcall_mtldevice_newmeshrenderpso, device) == 0 && sizeof(((struct unixcall_mtldevice_newmeshrenderpso *)0)->device) == 8, "ABI field 35:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newmeshrenderpso, info) == 8 && sizeof(((struct unixcall_mtldevice_newmeshrenderpso *)0)->info) == 8, "ABI field 35:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newmeshrenderpso, ret_error) == 16 && sizeof(((struct unixcall_mtldevice_newmeshrenderpso *)0)->ret_error) == 8, "ABI field 35:ret_error");
_Static_assert(offsetof(struct unixcall_mtldevice_newmeshrenderpso, ret_pso) == 24 && sizeof(((struct unixcall_mtldevice_newmeshrenderpso *)0)->ret_pso) == 8, "ABI field 35:ret_pso");
_Static_assert(sizeof(struct unixcall_generic_obj_cmd_noret) == 16, "ABI size 36");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, encoder) == 0 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->encoder) == 8, "ABI field 36:encoder");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, cmd_head) == 8 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->cmd_head) == 8, "ABI field 36:cmd_head");
_Static_assert(sizeof(struct unixcall_generic_obj_cmd_noret) == 16, "ABI size 37");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, encoder) == 0 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->encoder) == 8, "ABI field 37:encoder");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, cmd_head) == 8 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->cmd_head) == 8, "ABI field 37:cmd_head");
_Static_assert(sizeof(struct unixcall_generic_obj_cmd_noret) == 16, "ABI size 38");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, encoder) == 0 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->encoder) == 8, "ABI field 38:encoder");
_Static_assert(offsetof(struct unixcall_generic_obj_cmd_noret, cmd_head) == 8 && sizeof(((struct unixcall_generic_obj_cmd_noret *)0)->cmd_head) == 8, "ABI field 38:cmd_head");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 39");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 39:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 39:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 40");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 40:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 40:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 41");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 41:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 41:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 42");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 42:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 42:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 43");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 43:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 43:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 44");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 44:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 44:ret");
_Static_assert(sizeof(struct unixcall_mtltexture_replaceregion) == 96, "ABI size 45");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, texture) == 0 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->texture) == 8, "ABI field 45:texture");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, origin) == 8 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->origin) == 24, "ABI field 45:origin");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, size) == 32 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->size) == 24, "ABI field 45:size");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, level) == 56 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->level) == 8, "ABI field 45:level");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, slice) == 64 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->slice) == 8, "ABI field 45:slice");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, data) == 72 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->data) == 8, "ABI field 45:data");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, bytes_per_row) == 80 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->bytes_per_row) == 8, "ABI field 45:bytes_per_row");
_Static_assert(offsetof(struct unixcall_mtltexture_replaceregion, bytes_per_image) == 88 && sizeof(((struct unixcall_mtltexture_replaceregion *)0)->bytes_per_image) == 8, "ABI field 45:bytes_per_image");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 46");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 46:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 46:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 46:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_noret) == 16, "ABI size 47");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->handle) == 8, "ABI field 47:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->arg) == 8, "ABI field 47:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_double_noret) == 24, "ABI size 48");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_double_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_double_noret *)0)->handle) == 8, "ABI field 48:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_double_noret, arg0) == 8 && sizeof(((struct unixcall_generic_obj_obj_double_noret *)0)->arg0) == 8, "ABI field 48:arg0");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_double_noret, arg1) == 16 && sizeof(((struct unixcall_generic_obj_obj_double_noret *)0)->arg1) == 8, "ABI field 48:arg1");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 49");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 49:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 49:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 49:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 50");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 50:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 50:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 51");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 51:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 51:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 51:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 52");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 52:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 52:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 53");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 53:ret");
_Static_assert(sizeof(struct unixcall_mtlcapturemanager_startcapture) == 24, "ABI size 54");
_Static_assert(offsetof(struct unixcall_mtlcapturemanager_startcapture, capture_manager) == 0 && sizeof(((struct unixcall_mtlcapturemanager_startcapture *)0)->capture_manager) == 8, "ABI field 54:capture_manager");
_Static_assert(offsetof(struct unixcall_mtlcapturemanager_startcapture, info) == 8 && sizeof(((struct unixcall_mtlcapturemanager_startcapture *)0)->info) == 8, "ABI field 54:info");
_Static_assert(offsetof(struct unixcall_mtlcapturemanager_startcapture, ret) == 16 && sizeof(((struct unixcall_mtlcapturemanager_startcapture *)0)->ret) == 1, "ABI field 54:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 55");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 55:handle");
_Static_assert(sizeof(struct unixcall_mtldevice_newfxtemporalscaler) == 24, "ABI size 56");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxtemporalscaler, device) == 0 && sizeof(((struct unixcall_mtldevice_newfxtemporalscaler *)0)->device) == 8, "ABI field 56:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxtemporalscaler, info) == 8 && sizeof(((struct unixcall_mtldevice_newfxtemporalscaler *)0)->info) == 8, "ABI field 56:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxtemporalscaler, ret) == 16 && sizeof(((struct unixcall_mtldevice_newfxtemporalscaler *)0)->ret) == 8, "ABI field 56:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newfxspatialscaler) == 24, "ABI size 57");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxspatialscaler, device) == 0 && sizeof(((struct unixcall_mtldevice_newfxspatialscaler *)0)->device) == 8, "ABI field 57:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxspatialscaler, info) == 8 && sizeof(((struct unixcall_mtldevice_newfxspatialscaler *)0)->info) == 8, "ABI field 57:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newfxspatialscaler, ret) == 16 && sizeof(((struct unixcall_mtldevice_newfxspatialscaler *)0)->ret) == 8, "ABI field 57:ret");
_Static_assert(sizeof(struct unixcall_mtlcommandbuffer_temporal_scale) == 72, "ABI size 58");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, cmdbuf) == 0 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->cmdbuf) == 8, "ABI field 58:cmdbuf");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, scaler) == 8 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->scaler) == 8, "ABI field 58:scaler");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, color) == 16 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->color) == 8, "ABI field 58:color");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, output) == 24 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->output) == 8, "ABI field 58:output");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, depth) == 32 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->depth) == 8, "ABI field 58:depth");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, motion) == 40 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->motion) == 8, "ABI field 58:motion");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, exposure) == 48 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->exposure) == 8, "ABI field 58:exposure");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, fence) == 56 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->fence) == 8, "ABI field 58:fence");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, props) == 64 && sizeof(((struct unixcall_mtlcommandbuffer_temporal_scale *)0)->props) == 8, "ABI field 58:props");
_Static_assert(sizeof(struct unixcall_mtlcommandbuffer_spatial_scale) == 40, "ABI size 59");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_spatial_scale, cmdbuf) == 0 && sizeof(((struct unixcall_mtlcommandbuffer_spatial_scale *)0)->cmdbuf) == 8, "ABI field 59:cmdbuf");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_spatial_scale, scaler) == 8 && sizeof(((struct unixcall_mtlcommandbuffer_spatial_scale *)0)->scaler) == 8, "ABI field 59:scaler");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_spatial_scale, color) == 16 && sizeof(((struct unixcall_mtlcommandbuffer_spatial_scale *)0)->color) == 8, "ABI field 59:color");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_spatial_scale, output) == 24 && sizeof(((struct unixcall_mtlcommandbuffer_spatial_scale *)0)->output) == 8, "ABI field 59:output");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_spatial_scale, fence) == 32 && sizeof(((struct unixcall_mtlcommandbuffer_spatial_scale *)0)->fence) == 8, "ABI field 59:fence");
_Static_assert(sizeof(struct unixcall_nsstring_string) == 24, "ABI size 60");
_Static_assert(offsetof(struct unixcall_nsstring_string, buffer_ptr) == 0 && sizeof(((struct unixcall_nsstring_string *)0)->buffer_ptr) == 8, "ABI field 60:buffer_ptr");
_Static_assert(offsetof(struct unixcall_nsstring_string, encoding) == 8 && sizeof(((struct unixcall_nsstring_string *)0)->encoding) == 8, "ABI field 60:encoding");
_Static_assert(offsetof(struct unixcall_nsstring_string, ret) == 16 && sizeof(((struct unixcall_nsstring_string *)0)->ret) == 8, "ABI field 60:ret");
_Static_assert(sizeof(struct unixcall_nsstring_string) == 24, "ABI size 61");
_Static_assert(offsetof(struct unixcall_nsstring_string, buffer_ptr) == 0 && sizeof(((struct unixcall_nsstring_string *)0)->buffer_ptr) == 8, "ABI field 61:buffer_ptr");
_Static_assert(offsetof(struct unixcall_nsstring_string, encoding) == 8 && sizeof(((struct unixcall_nsstring_string *)0)->encoding) == 8, "ABI field 61:encoding");
_Static_assert(offsetof(struct unixcall_nsstring_string, ret) == 16 && sizeof(((struct unixcall_nsstring_string *)0)->ret) == 8, "ABI field 61:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 62");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 62:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_obj_uint64_ret) == 32, "ABI size 63");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_obj_uint64_ret *)0)->handle) == 8, "ABI field 63:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_uint64_ret, arg0) == 8 && sizeof(((struct unixcall_generic_obj_obj_obj_uint64_ret *)0)->arg0) == 8, "ABI field 63:arg0");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_uint64_ret, arg1) == 16 && sizeof(((struct unixcall_generic_obj_obj_obj_uint64_ret *)0)->arg1) == 8, "ABI field 63:arg1");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_uint64_ret, ret) == 24 && sizeof(((struct unixcall_generic_obj_obj_obj_uint64_ret *)0)->ret) == 8, "ABI field 63:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_obj_noret) == 24, "ABI size 64");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_obj_noret *)0)->handle) == 8, "ABI field 64:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_noret, arg0) == 8 && sizeof(((struct unixcall_generic_obj_obj_obj_noret *)0)->arg0) == 8, "ABI field 64:arg0");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_obj_noret, arg1) == 16 && sizeof(((struct unixcall_generic_obj_obj_obj_noret *)0)->arg1) == 8, "ABI field 64:arg1");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_noret) == 16, "ABI size 65");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->handle) == 8, "ABI field 65:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->arg) == 8, "ABI field 65:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 66");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 66:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 66:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 67");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 67:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 67:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 68");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 68:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 68:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 69");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 69:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 69:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_constptr_noret) == 16, "ABI size 70");
_Static_assert(offsetof(struct unixcall_generic_obj_constptr_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_constptr_noret *)0)->handle) == 8, "ABI field 70:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_constptr_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_constptr_noret *)0)->arg) == 8, "ABI field 70:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_ptr_noret) == 16, "ABI size 71");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->handle) == 8, "ABI field 71:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->arg) == 8, "ABI field 71:arg");
_Static_assert(sizeof(struct unixcall_create_metal_view_from_hwnd) == 32, "ABI size 72");
_Static_assert(offsetof(struct unixcall_create_metal_view_from_hwnd, hwnd) == 0 && sizeof(((struct unixcall_create_metal_view_from_hwnd *)0)->hwnd) == 8, "ABI field 72:hwnd");
_Static_assert(offsetof(struct unixcall_create_metal_view_from_hwnd, device) == 8 && sizeof(((struct unixcall_create_metal_view_from_hwnd *)0)->device) == 8, "ABI field 72:device");
_Static_assert(offsetof(struct unixcall_create_metal_view_from_hwnd, ret_view) == 16 && sizeof(((struct unixcall_create_metal_view_from_hwnd *)0)->ret_view) == 8, "ABI field 72:ret_view");
_Static_assert(offsetof(struct unixcall_create_metal_view_from_hwnd, ret_layer) == 24 && sizeof(((struct unixcall_create_metal_view_from_hwnd *)0)->ret_layer) == 8, "ABI field 72:ret_layer");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 73");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 73:handle");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_noret) == 16, "ABI size 86");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->handle) == 8, "ABI field 86:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_obj_noret *)0)->arg) == 8, "ABI field 86:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_noret) == 16, "ABI size 87");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_noret *)0)->handle) == 8, "ABI field 87:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_noret *)0)->arg) == 8, "ABI field 87:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 89");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 89:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 89:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 90");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 90:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 90:ret");
_Static_assert(sizeof(struct unixcall_enumerate) == 40, "ABI size 91");
_Static_assert(offsetof(struct unixcall_enumerate, enumerable) == 0 && sizeof(((struct unixcall_enumerate *)0)->enumerable) == 8, "ABI field 91:enumerable");
_Static_assert(offsetof(struct unixcall_enumerate, start) == 8 && sizeof(((struct unixcall_enumerate *)0)->start) == 8, "ABI field 91:start");
_Static_assert(offsetof(struct unixcall_enumerate, buffer_size) == 16 && sizeof(((struct unixcall_enumerate *)0)->buffer_size) == 8, "ABI field 91:buffer_size");
_Static_assert(offsetof(struct unixcall_enumerate, buffer) == 24 && sizeof(((struct unixcall_enumerate *)0)->buffer) == 8, "ABI field 91:buffer");
_Static_assert(offsetof(struct unixcall_enumerate, ret_read) == 32 && sizeof(((struct unixcall_enumerate *)0)->ret_read) == 8, "ABI field 91:ret_read");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 92");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 92:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 92:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 93");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 93:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 93:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 93:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 94");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 94:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 95");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 95:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_ptr_noret) == 16, "ABI size 96");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->handle) == 8, "ABI field 96:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->arg) == 8, "ABI field 96:arg");
_Static_assert(sizeof(struct unixcall_generic_obj_ptr_noret) == 16, "ABI size 97");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->handle) == 8, "ABI field 97:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_ptr_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_ptr_noret *)0)->arg) == 8, "ABI field 97:arg");
_Static_assert(sizeof(struct unixcall_mtllibrary_newfunction_with_constants) == 48, "ABI size 98");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, library) == 0 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->library) == 8, "ABI field 98:library");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, name) == 8 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->name) == 8, "ABI field 98:name");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, constants) == 16 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->constants) == 8, "ABI field 98:constants");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, num_constants) == 24 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->num_constants) == 8, "ABI field 98:num_constants");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, ret) == 32 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->ret) == 8, "ABI field 98:ret");
_Static_assert(offsetof(struct unixcall_mtllibrary_newfunction_with_constants, ret_error) == 40 && sizeof(((struct unixcall_mtllibrary_newfunction_with_constants *)0)->ret_error) == 8, "ABI field 98:ret_error");
_Static_assert(sizeof(struct unixcall_query_display_setting) == 32, "ABI size 99");
_Static_assert(offsetof(struct unixcall_query_display_setting, display_id) == 0 && sizeof(((struct unixcall_query_display_setting *)0)->display_id) == 8, "ABI field 99:display_id");
_Static_assert(offsetof(struct unixcall_query_display_setting, colorspace) == 8 && sizeof(((struct unixcall_query_display_setting *)0)->colorspace) == 8, "ABI field 99:colorspace");
_Static_assert(offsetof(struct unixcall_query_display_setting, hdr_metadata) == 16 && sizeof(((struct unixcall_query_display_setting *)0)->hdr_metadata) == 8, "ABI field 99:hdr_metadata");
_Static_assert(offsetof(struct unixcall_query_display_setting, ret) == 24 && sizeof(((struct unixcall_query_display_setting *)0)->ret) == 1, "ABI field 99:ret");
_Static_assert(sizeof(struct unixcall_update_display_setting) == 24, "ABI size 100");
_Static_assert(offsetof(struct unixcall_update_display_setting, display_id) == 0 && sizeof(((struct unixcall_update_display_setting *)0)->display_id) == 8, "ABI field 100:display_id");
_Static_assert(offsetof(struct unixcall_update_display_setting, colorspace) == 8 && sizeof(((struct unixcall_update_display_setting *)0)->colorspace) == 8, "ABI field 100:colorspace");
_Static_assert(offsetof(struct unixcall_update_display_setting, hdr_metadata) == 16 && sizeof(((struct unixcall_update_display_setting *)0)->hdr_metadata) == 8, "ABI field 100:hdr_metadata");
_Static_assert(sizeof(struct unixcall_query_display_setting_for_layer) == 40, "ABI size 101");
_Static_assert(offsetof(struct unixcall_query_display_setting_for_layer, layer) == 0 && sizeof(((struct unixcall_query_display_setting_for_layer *)0)->layer) == 8, "ABI field 101:layer");
_Static_assert(offsetof(struct unixcall_query_display_setting_for_layer, version) == 8 && sizeof(((struct unixcall_query_display_setting_for_layer *)0)->version) == 8, "ABI field 101:version");
_Static_assert(offsetof(struct unixcall_query_display_setting_for_layer, colorspace) == 16 && sizeof(((struct unixcall_query_display_setting_for_layer *)0)->colorspace) == 8, "ABI field 101:colorspace");
_Static_assert(offsetof(struct unixcall_query_display_setting_for_layer, hdr_metadata) == 24 && sizeof(((struct unixcall_query_display_setting_for_layer *)0)->hdr_metadata) == 8, "ABI field 101:hdr_metadata");
_Static_assert(offsetof(struct unixcall_query_display_setting_for_layer, edr_value) == 32 && sizeof(((struct unixcall_query_display_setting_for_layer *)0)->edr_value) == 8, "ABI field 101:edr_value");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_uint64_noret) == 24, "ABI size 102");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->handle) == 8, "ABI field 102:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, arg0) == 8 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->arg0) == 8, "ABI field 102:arg0");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_uint64_noret, arg1) == 16 && sizeof(((struct unixcall_generic_obj_obj_uint64_noret *)0)->arg1) == 8, "ABI field 102:arg1");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_noret) == 16, "ABI size 103");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_noret *)0)->handle) == 8, "ABI field 103:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_noret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_noret *)0)->arg) == 8, "ABI field 103:arg");
_Static_assert(sizeof(struct unixcall_mtlsharedevent_setevent) == 32, "ABI size 104");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_setevent, shared_event) == 0 && sizeof(((struct unixcall_mtlsharedevent_setevent *)0)->shared_event) == 8, "ABI field 104:shared_event");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_setevent, event_handle) == 8 && sizeof(((struct unixcall_mtlsharedevent_setevent *)0)->event_handle) == 8, "ABI field 104:event_handle");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_setevent, shared_event_listener) == 16 && sizeof(((struct unixcall_mtlsharedevent_setevent *)0)->shared_event_listener) == 8, "ABI field 104:shared_event_listener");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_setevent, value) == 24 && sizeof(((struct unixcall_mtlsharedevent_setevent *)0)->value) == 8, "ABI field 104:value");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 105");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 105:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 105:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_obj_ret) == 16, "ABI size 106");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->handle) == 8, "ABI field 106:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_obj_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_obj_ret *)0)->ret) == 8, "ABI field 106:ret");
_Static_assert(sizeof(struct unixcall_mtlbuffer_updatecontents) == 32, "ABI size 107");
_Static_assert(offsetof(struct unixcall_mtlbuffer_updatecontents, buffer) == 0 && sizeof(((struct unixcall_mtlbuffer_updatecontents *)0)->buffer) == 8, "ABI field 107:buffer");
_Static_assert(offsetof(struct unixcall_mtlbuffer_updatecontents, offset) == 8 && sizeof(((struct unixcall_mtlbuffer_updatecontents *)0)->offset) == 8, "ABI field 107:offset");
_Static_assert(offsetof(struct unixcall_mtlbuffer_updatecontents, data) == 16 && sizeof(((struct unixcall_mtlbuffer_updatecontents *)0)->data) == 8, "ABI field 107:data");
_Static_assert(offsetof(struct unixcall_mtlbuffer_updatecontents, length) == 24 && sizeof(((struct unixcall_mtlbuffer_updatecontents *)0)->length) == 8, "ABI field 107:length");
_Static_assert(sizeof(struct unixcall_generic_obj_ret) == 8, "ABI size 108");
_Static_assert(offsetof(struct unixcall_generic_obj_ret, ret) == 0 && sizeof(((struct unixcall_generic_obj_ret *)0)->ret) == 8, "ABI field 108:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 109");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 109:handle");
_Static_assert(sizeof(struct unixcall_generic_obj_noret) == 8, "ABI size 110");
_Static_assert(offsetof(struct unixcall_generic_obj_noret, handle) == 0 && sizeof(((struct unixcall_generic_obj_noret *)0)->handle) == 8, "ABI field 110:handle");
_Static_assert(sizeof(struct unixcall_get_os_version) == 24, "ABI size 111");
_Static_assert(offsetof(struct unixcall_get_os_version, ret_major) == 0 && sizeof(((struct unixcall_get_os_version *)0)->ret_major) == 8, "ABI field 111:ret_major");
_Static_assert(offsetof(struct unixcall_get_os_version, ret_minor) == 8 && sizeof(((struct unixcall_get_os_version *)0)->ret_minor) == 8, "ABI field 111:ret_minor");
_Static_assert(offsetof(struct unixcall_get_os_version, ret_patch) == 16 && sizeof(((struct unixcall_get_os_version *)0)->ret_patch) == 8, "ABI field 111:ret_patch");
_Static_assert(sizeof(struct unixcall_mtldevice_newbinaryarchive) == 32, "ABI size 112");
_Static_assert(offsetof(struct unixcall_mtldevice_newbinaryarchive, device) == 0 && sizeof(((struct unixcall_mtldevice_newbinaryarchive *)0)->device) == 8, "ABI field 112:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newbinaryarchive, url) == 8 && sizeof(((struct unixcall_mtldevice_newbinaryarchive *)0)->url) == 8, "ABI field 112:url");
_Static_assert(offsetof(struct unixcall_mtldevice_newbinaryarchive, ret_archive) == 16 && sizeof(((struct unixcall_mtldevice_newbinaryarchive *)0)->ret_archive) == 8, "ABI field 112:ret_archive");
_Static_assert(offsetof(struct unixcall_mtldevice_newbinaryarchive, ret_error) == 24 && sizeof(((struct unixcall_mtldevice_newbinaryarchive *)0)->ret_error) == 8, "ABI field 112:ret_error");
_Static_assert(sizeof(struct unixcall_mtlbinaryarchive_serialize) == 24, "ABI size 113");
_Static_assert(offsetof(struct unixcall_mtlbinaryarchive_serialize, archive) == 0 && sizeof(((struct unixcall_mtlbinaryarchive_serialize *)0)->archive) == 8, "ABI field 113:archive");
_Static_assert(offsetof(struct unixcall_mtlbinaryarchive_serialize, url) == 8 && sizeof(((struct unixcall_mtlbinaryarchive_serialize *)0)->url) == 8, "ABI field 113:url");
_Static_assert(offsetof(struct unixcall_mtlbinaryarchive_serialize, ret_error) == 16 && sizeof(((struct unixcall_mtlbinaryarchive_serialize *)0)->ret_error) == 8, "ABI field 113:ret_error");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_obj_ret) == 24, "ABI size 114");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->handle) == 8, "ABI field 114:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->arg) == 8, "ABI field 114:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_obj_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_obj_ret *)0)->ret) == 8, "ABI field 114:ret");
_Static_assert(sizeof(struct unixcall_cache_alloc_init) == 24, "ABI size 115");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, path) == 0 && sizeof(((struct unixcall_cache_alloc_init *)0)->path) == 8, "ABI field 115:path");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, version) == 8 && sizeof(((struct unixcall_cache_alloc_init *)0)->version) == 8, "ABI field 115:version");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, ret_cache) == 16 && sizeof(((struct unixcall_cache_alloc_init *)0)->ret_cache) == 8, "ABI field 115:ret_cache");
_Static_assert(sizeof(struct unixcall_cache_get) == 32, "ABI size 116");
_Static_assert(offsetof(struct unixcall_cache_get, cache) == 0 && sizeof(((struct unixcall_cache_get *)0)->cache) == 8, "ABI field 116:cache");
_Static_assert(offsetof(struct unixcall_cache_get, key) == 8 && sizeof(((struct unixcall_cache_get *)0)->key) == 8, "ABI field 116:key");
_Static_assert(offsetof(struct unixcall_cache_get, key_length) == 16 && sizeof(((struct unixcall_cache_get *)0)->key_length) == 8, "ABI field 116:key_length");
_Static_assert(offsetof(struct unixcall_cache_get, ret_data) == 24 && sizeof(((struct unixcall_cache_get *)0)->ret_data) == 8, "ABI field 116:ret_data");
_Static_assert(sizeof(struct unixcall_cache_alloc_init) == 24, "ABI size 117");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, path) == 0 && sizeof(((struct unixcall_cache_alloc_init *)0)->path) == 8, "ABI field 117:path");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, version) == 8 && sizeof(((struct unixcall_cache_alloc_init *)0)->version) == 8, "ABI field 117:version");
_Static_assert(offsetof(struct unixcall_cache_alloc_init, ret_cache) == 16 && sizeof(((struct unixcall_cache_alloc_init *)0)->ret_cache) == 8, "ABI field 117:ret_cache");
_Static_assert(sizeof(struct unixcall_cache_set) == 32, "ABI size 118");
_Static_assert(offsetof(struct unixcall_cache_set, cache) == 0 && sizeof(((struct unixcall_cache_set *)0)->cache) == 8, "ABI field 118:cache");
_Static_assert(offsetof(struct unixcall_cache_set, key) == 8 && sizeof(((struct unixcall_cache_set *)0)->key) == 8, "ABI field 118:key");
_Static_assert(offsetof(struct unixcall_cache_set, key_length) == 16 && sizeof(((struct unixcall_cache_set *)0)->key_length) == 8, "ABI field 118:key_length");
_Static_assert(offsetof(struct unixcall_cache_set, value_data) == 24 && sizeof(((struct unixcall_cache_set *)0)->value_data) == 8, "ABI field 118:value_data");
_Static_assert(sizeof(struct unixcall_setmetalcachepath) == 16, "ABI size 119");
_Static_assert(offsetof(struct unixcall_setmetalcachepath, path) == 0 && sizeof(((struct unixcall_setmetalcachepath *)0)->path) == 8, "ABI field 119:path");
_Static_assert(offsetof(struct unixcall_setmetalcachepath, ret_success) == 8 && sizeof(((struct unixcall_setmetalcachepath *)0)->ret_success) == 8, "ABI field 119:ret_success");
_Static_assert(sizeof(struct unixcall_mtldevice_newtexture) == 24, "ABI size 120");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, device) == 0 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->device) == 8, "ABI field 120:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, info) == 8 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->info) == 8, "ABI field 120:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newtexture, ret) == 16 && sizeof(((struct unixcall_mtldevice_newtexture *)0)->ret) == 8, "ABI field 120:ret");
_Static_assert(sizeof(struct unixcall_bootstrap) == 136, "ABI size 121");
_Static_assert(offsetof(struct unixcall_bootstrap, name) == 0 && sizeof(((struct unixcall_bootstrap *)0)->name) == 128, "ABI field 121:name");
_Static_assert(offsetof(struct unixcall_bootstrap, mach_port) == 128 && sizeof(((struct unixcall_bootstrap *)0)->mach_port) == 4, "ABI field 121:mach_port");
_Static_assert(offsetof(struct unixcall_bootstrap, reserved) == 132 && sizeof(((struct unixcall_bootstrap *)0)->reserved) == 4, "ABI field 121:reserved");
_Static_assert(sizeof(struct unixcall_bootstrap) == 136, "ABI size 122");
_Static_assert(offsetof(struct unixcall_bootstrap, name) == 0 && sizeof(((struct unixcall_bootstrap *)0)->name) == 128, "ABI field 122:name");
_Static_assert(offsetof(struct unixcall_bootstrap, mach_port) == 128 && sizeof(((struct unixcall_bootstrap *)0)->mach_port) == 4, "ABI field 122:mach_port");
_Static_assert(offsetof(struct unixcall_bootstrap, reserved) == 132 && sizeof(((struct unixcall_bootstrap *)0)->reserved) == 4, "ABI field 122:reserved");
_Static_assert(sizeof(struct unixcall_mtlsharedevent_createmachport) == 16, "ABI size 123");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_createmachport, event) == 0 && sizeof(((struct unixcall_mtlsharedevent_createmachport *)0)->event) == 8, "ABI field 123:event");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_createmachport, ret_mach_port) == 8 && sizeof(((struct unixcall_mtlsharedevent_createmachport *)0)->ret_mach_port) == 4, "ABI field 123:ret_mach_port");
_Static_assert(sizeof(struct unixcall_mtldevice_newsharedeventwithmachport) == 24, "ABI size 124");
_Static_assert(offsetof(struct unixcall_mtldevice_newsharedeventwithmachport, device) == 0 && sizeof(((struct unixcall_mtldevice_newsharedeventwithmachport *)0)->device) == 8, "ABI field 124:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newsharedeventwithmachport, mach_port) == 8 && sizeof(((struct unixcall_mtldevice_newsharedeventwithmachport *)0)->mach_port) == 4, "ABI field 124:mach_port");
_Static_assert(offsetof(struct unixcall_mtldevice_newsharedeventwithmachport, ret_event) == 16 && sizeof(((struct unixcall_mtldevice_newsharedeventwithmachport *)0)->ret_event) == 8, "ABI field 124:ret_event");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_ret) == 16, "ABI size 125");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->handle) == 8, "ABI field 125:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_ret, ret) == 8 && sizeof(((struct unixcall_generic_obj_uint64_ret *)0)->ret) == 8, "ABI field 125:ret");
_Static_assert(sizeof(struct unixcall_mtlsharedevent_waituntilsignaledvalue) == 32, "ABI size 126");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_waituntilsignaledvalue, event) == 0 && sizeof(((struct unixcall_mtlsharedevent_waituntilsignaledvalue *)0)->event) == 8, "ABI field 126:event");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_waituntilsignaledvalue, value) == 8 && sizeof(((struct unixcall_mtlsharedevent_waituntilsignaledvalue *)0)->value) == 8, "ABI field 126:value");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_waituntilsignaledvalue, timeout_ms) == 16 && sizeof(((struct unixcall_mtlsharedevent_waituntilsignaledvalue *)0)->timeout_ms) == 8, "ABI field 126:timeout_ms");
_Static_assert(offsetof(struct unixcall_mtlsharedevent_waituntilsignaledvalue, ret_timeout) == 24 && sizeof(((struct unixcall_mtlsharedevent_waituntilsignaledvalue *)0)->ret_timeout) == 1, "ABI field 126:ret_timeout");
_Static_assert(sizeof(struct unixcall_mtlcountersamplebuffer_newtimestampbuffer) == 24, "ABI size 127");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_newtimestampbuffer, device) == 0 && sizeof(((struct unixcall_mtlcountersamplebuffer_newtimestampbuffer *)0)->device) == 8, "ABI field 127:device");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_newtimestampbuffer, sample_count) == 8 && sizeof(((struct unixcall_mtlcountersamplebuffer_newtimestampbuffer *)0)->sample_count) == 4, "ABI field 127:sample_count");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_newtimestampbuffer, shared) == 12 && sizeof(((struct unixcall_mtlcountersamplebuffer_newtimestampbuffer *)0)->shared) == 4, "ABI field 127:shared");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_newtimestampbuffer, ret) == 16 && sizeof(((struct unixcall_mtlcountersamplebuffer_newtimestampbuffer *)0)->ret) == 8, "ABI field 127:ret");
_Static_assert(sizeof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange) == 32, "ABI size 128");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange, sample_buffer) == 0 && sizeof(((struct unixcall_mtlcountersamplebuffer_resolvecounterrange *)0)->sample_buffer) == 8, "ABI field 128:sample_buffer");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange, start) == 8 && sizeof(((struct unixcall_mtlcountersamplebuffer_resolvecounterrange *)0)->start) == 4, "ABI field 128:start");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange, len) == 12 && sizeof(((struct unixcall_mtlcountersamplebuffer_resolvecounterrange *)0)->len) == 4, "ABI field 128:len");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange, data_out) == 16 && sizeof(((struct unixcall_mtlcountersamplebuffer_resolvecounterrange *)0)->data_out) == 8, "ABI field 128:data_out");
_Static_assert(offsetof(struct unixcall_mtlcountersamplebuffer_resolvecounterrange, data_length) == 24 && sizeof(((struct unixcall_mtlcountersamplebuffer_resolvecounterrange *)0)->data_length) == 8, "ABI field 128:data_length");
_Static_assert(sizeof(struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers) == 32, "ABI size 129");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers, cmdbuf) == 0 && sizeof(((struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers *)0)->cmdbuf) == 8, "ABI field 129:cmdbuf");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers, attachments) == 8 && sizeof(((struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers *)0)->attachments) == 8, "ABI field 129:attachments");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers, num_attachments) == 16 && sizeof(((struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers *)0)->num_attachments) == 8, "ABI field 129:num_attachments");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers, ret) == 24 && sizeof(((struct unixcall_mtlcommandbuffer_blitcommandencoderwithsamplebuffers *)0)->ret) == 8, "ABI field 129:ret");
_Static_assert(sizeof(struct unixcall_generic_obj_uint64_uint64_ret) == 24, "ABI size 130");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, handle) == 0 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->handle) == 8, "ABI field 130:handle");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, arg) == 8 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->arg) == 8, "ABI field 130:arg");
_Static_assert(offsetof(struct unixcall_generic_obj_uint64_uint64_ret, ret) == 16 && sizeof(((struct unixcall_generic_obj_uint64_uint64_ret *)0)->ret) == 8, "ABI field 130:ret");
_Static_assert(sizeof(struct unixcall_mtldevice_newrenderpso) == 32, "ABI size 131");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, device) == 0 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->device) == 8, "ABI field 131:device");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, info) == 8 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->info) == 8, "ABI field 131:info");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, ret_error) == 16 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->ret_error) == 8, "ABI field 131:ret_error");
_Static_assert(offsetof(struct unixcall_mtldevice_newrenderpso, ret_pso) == 24 && sizeof(((struct unixcall_mtldevice_newrenderpso *)0)->ret_pso) == 8, "ABI field 131:ret_pso");
_Static_assert(sizeof(struct unixcall_mtlcommandbuffer_frame_dump) == 24, "ABI size 132");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_frame_dump, cmdbuf) == 0 && sizeof(((struct unixcall_mtlcommandbuffer_frame_dump *)0)->cmdbuf) == 8, "ABI field 132:cmdbuf");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_frame_dump, texture) == 8 && sizeof(((struct unixcall_mtlcommandbuffer_frame_dump *)0)->texture) == 8, "ABI field 132:texture");
_Static_assert(offsetof(struct unixcall_mtlcommandbuffer_frame_dump, frame) == 16 && sizeof(((struct unixcall_mtlcommandbuffer_frame_dump *)0)->frame) == 8, "ABI field 132:frame");
_Static_assert(sizeof(struct unixcall_mtlbuffer_tracefields) == 40, "ABI size 133");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, buffer) == 0 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->buffer) == 8, "ABI field 133:buffer");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, offset) == 8 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->offset) == 8, "ABI field 133:offset");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, count) == 16 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->count) == 8, "ABI field 133:count");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, stride) == 24 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->stride) == 8, "ABI field 133:stride");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, kind) == 32 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->kind) == 4, "ABI field 133:kind");
_Static_assert(offsetof(struct unixcall_mtlbuffer_tracefields, reserved) == 36 && sizeof(((struct unixcall_mtlbuffer_tracefields *)0)->reserved) == 4, "ABI field 133:reserved");
_Static_assert(sizeof(struct unixcall_mtlbuffer_traceownership) == 32, "ABI size 134");
_Static_assert(offsetof(struct unixcall_mtlbuffer_traceownership, buffer) == 0 && sizeof(((struct unixcall_mtlbuffer_traceownership *)0)->buffer) == 8, "ABI field 134:buffer");
_Static_assert(offsetof(struct unixcall_mtlbuffer_traceownership, offset) == 8 && sizeof(((struct unixcall_mtlbuffer_traceownership *)0)->offset) == 8, "ABI field 134:offset");
_Static_assert(offsetof(struct unixcall_mtlbuffer_traceownership, length) == 16 && sizeof(((struct unixcall_mtlbuffer_traceownership *)0)->length) == 8, "ABI field 134:length");
_Static_assert(offsetof(struct unixcall_mtlbuffer_traceownership, action) == 24 && sizeof(((struct unixcall_mtlbuffer_traceownership *)0)->action) == 4, "ABI field 134:action");
_Static_assert(offsetof(struct unixcall_mtlbuffer_traceownership, reserved) == 28 && sizeof(((struct unixcall_mtlbuffer_traceownership *)0)->reserved) == 4, "ABI field 134:reserved");
