case 29: {
 if (root!=offsetof(struct unixcall_mtldevice_newcomputepso,info) || bytes.length!=sizeof(struct WMTComputePipelineInfo)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTComputePipelineInfo)];
 NSMutableSet *expected=[NSMutableSet set];
 [expected addObject:@(offsetof(struct WMTComputePipelineInfo,compute_function))];
 [expected addObject:@(offsetof(struct WMTComputePipelineInfo,binary_archive_for_serialization))];
 memset((char *)mask.mutableBytes+offsetof(struct WMTComputePipelineInfo,num_binary_archives_for_lookup),1,sizeof(((struct WMTComputePipelineInfo *)0)->num_binary_archives_for_lookup));
 memset((char *)mask.mutableBytes+offsetof(struct WMTComputePipelineInfo,fail_on_binary_archive_miss),1,sizeof(((struct WMTComputePipelineInfo *)0)->fail_on_binary_archive_miss));
 memset((char *)mask.mutableBytes+offsetof(struct WMTComputePipelineInfo,tgsize_is_multiple_of_sgwidth),1,sizeof(((struct WMTComputePipelineInfo *)0)->tgsize_is_multiple_of_sgwidth));
 memset((char *)mask.mutableBytes+offsetof(struct WMTComputePipelineInfo,immutable_buffers),1,sizeof(((struct WMTComputePipelineInfo *)0)->immutable_buffers));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
case 35: {
 if (root!=offsetof(struct unixcall_mtldevice_newmeshrenderpso,info) || bytes.length!=sizeof(struct WMTMeshRenderPipelineInfo)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTMeshRenderPipelineInfo)];
 NSMutableSet *expected=[NSMutableSet set];
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].rgb_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].rgb_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].alpha_blend_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].alpha_blend_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].src_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].src_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].dst_rgb_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].dst_rgb_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].src_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].src_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].dst_alpha_blend_factor),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].dst_alpha_blend_factor));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].write_mask),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].write_mask));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[0].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[0].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[1].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[1].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[2].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[2].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[3].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[3].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[4].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[4].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[5].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[5].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[6].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[6].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,colors[7].blending_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->colors[7].blending_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,alpha_to_coverage_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->alpha_to_coverage_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,logic_operation_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->logic_operation_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,logic_operation),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->logic_operation));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,rasterization_enabled),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->rasterization_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,raster_sample_count),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->raster_sample_count));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,depth_pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->depth_pixel_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,stencil_pixel_format),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->stencil_pixel_format));
 [expected addObject:@(offsetof(struct WMTMeshRenderPipelineInfo,object_function))];
 [expected addObject:@(offsetof(struct WMTMeshRenderPipelineInfo,mesh_function))];
 [expected addObject:@(offsetof(struct WMTMeshRenderPipelineInfo,fragment_function))];
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,immutable_object_buffers),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->immutable_object_buffers));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,immutable_mesh_buffers),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->immutable_mesh_buffers));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,immutable_fragment_buffers),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->immutable_fragment_buffers));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,payload_memory_length),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->payload_memory_length));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,mesh_tgsize_is_multiple_of_sgwidth),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->mesh_tgsize_is_multiple_of_sgwidth));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,object_tgsize_is_multiple_of_sgwidth),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->object_tgsize_is_multiple_of_sgwidth));
 [expected addObject:@(offsetof(struct WMTMeshRenderPipelineInfo,binary_archive_for_serialization))];
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,num_binary_archives_for_lookup),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->num_binary_archives_for_lookup));
 memset((char *)mask.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo,fail_on_binary_archive_miss),1,sizeof(((struct WMTMeshRenderPipelineInfo *)0)->fail_on_binary_archive_miss));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
case 56: {
 if (root!=offsetof(struct unixcall_mtldevice_newfxtemporalscaler,info) || bytes.length!=sizeof(struct WMTFXTemporalScalerInfo)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTFXTemporalScalerInfo)];
 NSMutableSet *expected=[NSMutableSet set];
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,color_format),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->color_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,output_format),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->output_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,depth_format),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->depth_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,motion_format),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->motion_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,input_width),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->input_width));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,input_height),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->input_height));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,output_width),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->output_width));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,output_height),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->output_height));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,input_content_min_scale),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->input_content_min_scale));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,input_content_max_scale),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->input_content_max_scale));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,auto_exposure),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->auto_exposure));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,input_content_properties_enabled),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->input_content_properties_enabled));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo,requires_synchronous_initialization),1,sizeof(((struct WMTFXTemporalScalerInfo *)0)->requires_synchronous_initialization));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
case 57: {
 if (root!=offsetof(struct unixcall_mtldevice_newfxspatialscaler,info) || bytes.length!=sizeof(struct WMTFXSpatialScalerInfo)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTFXSpatialScalerInfo)];
 NSMutableSet *expected=[NSMutableSet set];
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,color_format),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->color_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,output_format),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->output_format));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,input_width),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->input_width));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,input_height),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->input_height));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,output_width),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->output_width));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo,output_height),1,sizeof(((struct WMTFXSpatialScalerInfo *)0)->output_height));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
case 58: {
 if (root!=offsetof(struct unixcall_mtlcommandbuffer_temporal_scale,props) || bytes.length!=sizeof(struct WMTFXTemporalScalerProps)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTFXTemporalScalerProps)];
 NSMutableSet *expected=[NSMutableSet set];
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,input_content_width),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->input_content_width));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,input_content_height),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->input_content_height));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,reset),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->reset));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,depth_reversed),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->depth_reversed));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,motion_vector_scale_x),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->motion_vector_scale_x));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,motion_vector_scale_y),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->motion_vector_scale_y));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,jitter_offset_x),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->jitter_offset_x));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,jitter_offset_y),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->jitter_offset_y));
 memset((char *)mask.mutableBytes+offsetof(struct WMTFXTemporalScalerProps,pre_exposure),1,sizeof(((struct WMTFXTemporalScalerProps *)0)->pre_exposure));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
case 131: {
 if (root!=offsetof(struct unixcall_mtldevice_newrenderpso,info) || bytes.length!=sizeof(struct WMTTileRenderPipelineInfo)) return NO;
 NSMutableData *mask=[NSMutableData dataWithLength:sizeof(struct WMTTileRenderPipelineInfo)];
 NSMutableSet *expected=[NSMutableSet set];
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[0]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[0]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[1]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[1]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[2]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[2]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[3]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[3]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[4]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[4]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[5]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[5]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[6]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[6]));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,color_formats[7]),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->color_formats[7]));
 [expected addObject:@(offsetof(struct WMTTileRenderPipelineInfo,tile_function))];
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,immutable_tile_buffers),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->immutable_tile_buffers));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,raster_sample_count),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->raster_sample_count));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,tgsize_matches_tile_size),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->tgsize_matches_tile_size));
 [expected addObject:@(offsetof(struct WMTTileRenderPipelineInfo,binary_archive_for_serialization))];
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,num_binary_archives_for_lookup),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->num_binary_archives_for_lookup));
 memset((char *)mask.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo,fail_on_binary_archive_miss),1,sizeof(((struct WMTTileRenderPipelineInfo *)0)->fail_on_binary_archive_miss));
 return wmt_trace_api_validate_layout(bytes,relocations,mask,expected,@"MetalObject");
}
