case 29: {
  const struct WMTComputePipelineInfo *info = ((struct unixcall_mtldevice_newcomputepso *)params)->info.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 29");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTComputePipelineInfo)];
  NSMutableArray *handles = [NSMutableArray array];
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTComputePipelineInfo, compute_function), (id)info->compute_function, @"MetalObject", NO);
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTComputePipelineInfo, binary_archive_for_serialization), (id)info->binary_archive_for_serialization, @"MetalObject", NO);
  memcpy((char *)data.mutableBytes+offsetof(struct WMTComputePipelineInfo, num_binary_archives_for_lookup), &info->num_binary_archives_for_lookup, sizeof(info->num_binary_archives_for_lookup));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTComputePipelineInfo, fail_on_binary_archive_miss), &info->fail_on_binary_archive_miss, sizeof(info->fail_on_binary_archive_miss));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTComputePipelineInfo, tgsize_is_multiple_of_sgwidth), &info->tgsize_is_multiple_of_sgwidth, sizeof(info->tgsize_is_multiple_of_sgwidth));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTComputePipelineInfo, immutable_buffers), &info->immutable_buffers, sizeof(info->immutable_buffers));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtldevice_newcomputepso, info))} mutableCopy];
  if (info->num_binary_archives_for_lookup || info->binary_archive_for_serialization) {
    [payload release]; return wmt_trace_api_pack_failure(packet, @"binary archive consumer requires captured archive bytes; projection is not sufficient");
  }
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
case 35: {
  const struct WMTMeshRenderPipelineInfo *info = ((struct unixcall_mtldevice_newmeshrenderpso *)params)->info.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 35");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTMeshRenderPipelineInfo)];
  NSMutableArray *handles = [NSMutableArray array];
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].pixel_format), &info->colors[0].pixel_format, sizeof(info->colors[0].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].pixel_format), &info->colors[1].pixel_format, sizeof(info->colors[1].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].pixel_format), &info->colors[2].pixel_format, sizeof(info->colors[2].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].pixel_format), &info->colors[3].pixel_format, sizeof(info->colors[3].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].pixel_format), &info->colors[4].pixel_format, sizeof(info->colors[4].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].pixel_format), &info->colors[5].pixel_format, sizeof(info->colors[5].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].pixel_format), &info->colors[6].pixel_format, sizeof(info->colors[6].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].pixel_format), &info->colors[7].pixel_format, sizeof(info->colors[7].pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].rgb_blend_operation), &info->colors[0].rgb_blend_operation, sizeof(info->colors[0].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].rgb_blend_operation), &info->colors[1].rgb_blend_operation, sizeof(info->colors[1].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].rgb_blend_operation), &info->colors[2].rgb_blend_operation, sizeof(info->colors[2].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].rgb_blend_operation), &info->colors[3].rgb_blend_operation, sizeof(info->colors[3].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].rgb_blend_operation), &info->colors[4].rgb_blend_operation, sizeof(info->colors[4].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].rgb_blend_operation), &info->colors[5].rgb_blend_operation, sizeof(info->colors[5].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].rgb_blend_operation), &info->colors[6].rgb_blend_operation, sizeof(info->colors[6].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].rgb_blend_operation), &info->colors[7].rgb_blend_operation, sizeof(info->colors[7].rgb_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].alpha_blend_operation), &info->colors[0].alpha_blend_operation, sizeof(info->colors[0].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].alpha_blend_operation), &info->colors[1].alpha_blend_operation, sizeof(info->colors[1].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].alpha_blend_operation), &info->colors[2].alpha_blend_operation, sizeof(info->colors[2].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].alpha_blend_operation), &info->colors[3].alpha_blend_operation, sizeof(info->colors[3].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].alpha_blend_operation), &info->colors[4].alpha_blend_operation, sizeof(info->colors[4].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].alpha_blend_operation), &info->colors[5].alpha_blend_operation, sizeof(info->colors[5].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].alpha_blend_operation), &info->colors[6].alpha_blend_operation, sizeof(info->colors[6].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].alpha_blend_operation), &info->colors[7].alpha_blend_operation, sizeof(info->colors[7].alpha_blend_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].src_rgb_blend_factor), &info->colors[0].src_rgb_blend_factor, sizeof(info->colors[0].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].src_rgb_blend_factor), &info->colors[1].src_rgb_blend_factor, sizeof(info->colors[1].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].src_rgb_blend_factor), &info->colors[2].src_rgb_blend_factor, sizeof(info->colors[2].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].src_rgb_blend_factor), &info->colors[3].src_rgb_blend_factor, sizeof(info->colors[3].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].src_rgb_blend_factor), &info->colors[4].src_rgb_blend_factor, sizeof(info->colors[4].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].src_rgb_blend_factor), &info->colors[5].src_rgb_blend_factor, sizeof(info->colors[5].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].src_rgb_blend_factor), &info->colors[6].src_rgb_blend_factor, sizeof(info->colors[6].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].src_rgb_blend_factor), &info->colors[7].src_rgb_blend_factor, sizeof(info->colors[7].src_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].dst_rgb_blend_factor), &info->colors[0].dst_rgb_blend_factor, sizeof(info->colors[0].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].dst_rgb_blend_factor), &info->colors[1].dst_rgb_blend_factor, sizeof(info->colors[1].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].dst_rgb_blend_factor), &info->colors[2].dst_rgb_blend_factor, sizeof(info->colors[2].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].dst_rgb_blend_factor), &info->colors[3].dst_rgb_blend_factor, sizeof(info->colors[3].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].dst_rgb_blend_factor), &info->colors[4].dst_rgb_blend_factor, sizeof(info->colors[4].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].dst_rgb_blend_factor), &info->colors[5].dst_rgb_blend_factor, sizeof(info->colors[5].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].dst_rgb_blend_factor), &info->colors[6].dst_rgb_blend_factor, sizeof(info->colors[6].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].dst_rgb_blend_factor), &info->colors[7].dst_rgb_blend_factor, sizeof(info->colors[7].dst_rgb_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].src_alpha_blend_factor), &info->colors[0].src_alpha_blend_factor, sizeof(info->colors[0].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].src_alpha_blend_factor), &info->colors[1].src_alpha_blend_factor, sizeof(info->colors[1].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].src_alpha_blend_factor), &info->colors[2].src_alpha_blend_factor, sizeof(info->colors[2].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].src_alpha_blend_factor), &info->colors[3].src_alpha_blend_factor, sizeof(info->colors[3].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].src_alpha_blend_factor), &info->colors[4].src_alpha_blend_factor, sizeof(info->colors[4].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].src_alpha_blend_factor), &info->colors[5].src_alpha_blend_factor, sizeof(info->colors[5].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].src_alpha_blend_factor), &info->colors[6].src_alpha_blend_factor, sizeof(info->colors[6].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].src_alpha_blend_factor), &info->colors[7].src_alpha_blend_factor, sizeof(info->colors[7].src_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].dst_alpha_blend_factor), &info->colors[0].dst_alpha_blend_factor, sizeof(info->colors[0].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].dst_alpha_blend_factor), &info->colors[1].dst_alpha_blend_factor, sizeof(info->colors[1].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].dst_alpha_blend_factor), &info->colors[2].dst_alpha_blend_factor, sizeof(info->colors[2].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].dst_alpha_blend_factor), &info->colors[3].dst_alpha_blend_factor, sizeof(info->colors[3].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].dst_alpha_blend_factor), &info->colors[4].dst_alpha_blend_factor, sizeof(info->colors[4].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].dst_alpha_blend_factor), &info->colors[5].dst_alpha_blend_factor, sizeof(info->colors[5].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].dst_alpha_blend_factor), &info->colors[6].dst_alpha_blend_factor, sizeof(info->colors[6].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].dst_alpha_blend_factor), &info->colors[7].dst_alpha_blend_factor, sizeof(info->colors[7].dst_alpha_blend_factor));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].write_mask), &info->colors[0].write_mask, sizeof(info->colors[0].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].write_mask), &info->colors[1].write_mask, sizeof(info->colors[1].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].write_mask), &info->colors[2].write_mask, sizeof(info->colors[2].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].write_mask), &info->colors[3].write_mask, sizeof(info->colors[3].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].write_mask), &info->colors[4].write_mask, sizeof(info->colors[4].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].write_mask), &info->colors[5].write_mask, sizeof(info->colors[5].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].write_mask), &info->colors[6].write_mask, sizeof(info->colors[6].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].write_mask), &info->colors[7].write_mask, sizeof(info->colors[7].write_mask));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[0].blending_enabled), &info->colors[0].blending_enabled, sizeof(info->colors[0].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[1].blending_enabled), &info->colors[1].blending_enabled, sizeof(info->colors[1].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[2].blending_enabled), &info->colors[2].blending_enabled, sizeof(info->colors[2].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[3].blending_enabled), &info->colors[3].blending_enabled, sizeof(info->colors[3].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[4].blending_enabled), &info->colors[4].blending_enabled, sizeof(info->colors[4].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[5].blending_enabled), &info->colors[5].blending_enabled, sizeof(info->colors[5].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[6].blending_enabled), &info->colors[6].blending_enabled, sizeof(info->colors[6].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, colors[7].blending_enabled), &info->colors[7].blending_enabled, sizeof(info->colors[7].blending_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, alpha_to_coverage_enabled), &info->alpha_to_coverage_enabled, sizeof(info->alpha_to_coverage_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, logic_operation_enabled), &info->logic_operation_enabled, sizeof(info->logic_operation_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, logic_operation), &info->logic_operation, sizeof(info->logic_operation));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, rasterization_enabled), &info->rasterization_enabled, sizeof(info->rasterization_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, raster_sample_count), &info->raster_sample_count, sizeof(info->raster_sample_count));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, depth_pixel_format), &info->depth_pixel_format, sizeof(info->depth_pixel_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, stencil_pixel_format), &info->stencil_pixel_format, sizeof(info->stencil_pixel_format));
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTMeshRenderPipelineInfo, object_function), (id)info->object_function, @"MetalObject", NO);
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTMeshRenderPipelineInfo, mesh_function), (id)info->mesh_function, @"MetalObject", NO);
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTMeshRenderPipelineInfo, fragment_function), (id)info->fragment_function, @"MetalObject", NO);
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, immutable_object_buffers), &info->immutable_object_buffers, sizeof(info->immutable_object_buffers));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, immutable_mesh_buffers), &info->immutable_mesh_buffers, sizeof(info->immutable_mesh_buffers));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, immutable_fragment_buffers), &info->immutable_fragment_buffers, sizeof(info->immutable_fragment_buffers));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, payload_memory_length), &info->payload_memory_length, sizeof(info->payload_memory_length));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, mesh_tgsize_is_multiple_of_sgwidth), &info->mesh_tgsize_is_multiple_of_sgwidth, sizeof(info->mesh_tgsize_is_multiple_of_sgwidth));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, object_tgsize_is_multiple_of_sgwidth), &info->object_tgsize_is_multiple_of_sgwidth, sizeof(info->object_tgsize_is_multiple_of_sgwidth));
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTMeshRenderPipelineInfo, binary_archive_for_serialization), (id)info->binary_archive_for_serialization, @"MetalObject", NO);
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, num_binary_archives_for_lookup), &info->num_binary_archives_for_lookup, sizeof(info->num_binary_archives_for_lookup));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTMeshRenderPipelineInfo, fail_on_binary_archive_miss), &info->fail_on_binary_archive_miss, sizeof(info->fail_on_binary_archive_miss));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtldevice_newmeshrenderpso, info))} mutableCopy];
  if (info->num_binary_archives_for_lookup || info->binary_archive_for_serialization) {
    [payload release]; return wmt_trace_api_pack_failure(packet, @"binary archive consumer requires captured archive bytes; projection is not sufficient");
  }
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
case 56: {
  const struct WMTFXTemporalScalerInfo *info = ((struct unixcall_mtldevice_newfxtemporalscaler *)params)->info.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 56");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTFXTemporalScalerInfo)];
  NSMutableArray *handles = [NSMutableArray array];
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, color_format), &info->color_format, sizeof(info->color_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, output_format), &info->output_format, sizeof(info->output_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, depth_format), &info->depth_format, sizeof(info->depth_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, motion_format), &info->motion_format, sizeof(info->motion_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, input_width), &info->input_width, sizeof(info->input_width));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, input_height), &info->input_height, sizeof(info->input_height));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, output_width), &info->output_width, sizeof(info->output_width));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, output_height), &info->output_height, sizeof(info->output_height));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, input_content_min_scale), &info->input_content_min_scale, sizeof(info->input_content_min_scale));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, input_content_max_scale), &info->input_content_max_scale, sizeof(info->input_content_max_scale));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, auto_exposure), &info->auto_exposure, sizeof(info->auto_exposure));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, input_content_properties_enabled), &info->input_content_properties_enabled, sizeof(info->input_content_properties_enabled));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerInfo, requires_synchronous_initialization), &info->requires_synchronous_initialization, sizeof(info->requires_synchronous_initialization));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtldevice_newfxtemporalscaler, info))} mutableCopy];
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
case 57: {
  const struct WMTFXSpatialScalerInfo *info = ((struct unixcall_mtldevice_newfxspatialscaler *)params)->info.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 57");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTFXSpatialScalerInfo)];
  NSMutableArray *handles = [NSMutableArray array];
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, color_format), &info->color_format, sizeof(info->color_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, output_format), &info->output_format, sizeof(info->output_format));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, input_width), &info->input_width, sizeof(info->input_width));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, input_height), &info->input_height, sizeof(info->input_height));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, output_width), &info->output_width, sizeof(info->output_width));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXSpatialScalerInfo, output_height), &info->output_height, sizeof(info->output_height));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtldevice_newfxspatialscaler, info))} mutableCopy];
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
case 58: {
  const struct WMTFXTemporalScalerProps *info = ((struct unixcall_mtlcommandbuffer_temporal_scale *)params)->props.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 58");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTFXTemporalScalerProps)];
  NSMutableArray *handles = [NSMutableArray array];
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, input_content_width), &info->input_content_width, sizeof(info->input_content_width));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, input_content_height), &info->input_content_height, sizeof(info->input_content_height));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, reset), &info->reset, sizeof(info->reset));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, depth_reversed), &info->depth_reversed, sizeof(info->depth_reversed));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, motion_vector_scale_x), &info->motion_vector_scale_x, sizeof(info->motion_vector_scale_x));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, motion_vector_scale_y), &info->motion_vector_scale_y, sizeof(info->motion_vector_scale_y));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, jitter_offset_x), &info->jitter_offset_x, sizeof(info->jitter_offset_x));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, jitter_offset_y), &info->jitter_offset_y, sizeof(info->jitter_offset_y));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTFXTemporalScalerProps, pre_exposure), &info->pre_exposure, sizeof(info->pre_exposure));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtlcommandbuffer_temporal_scale, props))} mutableCopy];
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
case 131: {
  const struct WMTTileRenderPipelineInfo *info = ((struct unixcall_mtldevice_newrenderpso *)params)->info.ptr;
  if (!info) return wmt_trace_api_pack_failure(packet, @"nil descriptor 131");
  NSMutableData *data = [NSMutableData dataWithLength:sizeof(struct WMTTileRenderPipelineInfo)];
  NSMutableArray *handles = [NSMutableArray array];
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[0]), &info->color_formats[0], sizeof(info->color_formats[0]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[1]), &info->color_formats[1], sizeof(info->color_formats[1]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[2]), &info->color_formats[2], sizeof(info->color_formats[2]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[3]), &info->color_formats[3], sizeof(info->color_formats[3]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[4]), &info->color_formats[4], sizeof(info->color_formats[4]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[5]), &info->color_formats[5], sizeof(info->color_formats[5]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[6]), &info->color_formats[6], sizeof(info->color_formats[6]));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, color_formats[7]), &info->color_formats[7], sizeof(info->color_formats[7]));
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTTileRenderPipelineInfo, tile_function), (id)info->tile_function, @"MetalObject", NO);
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, immutable_tile_buffers), &info->immutable_tile_buffers, sizeof(info->immutable_tile_buffers));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, raster_sample_count), &info->raster_sample_count, sizeof(info->raster_sample_count));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, tgsize_matches_tile_size), &info->tgsize_matches_tile_size, sizeof(info->tgsize_matches_tile_size));
  wmt_trace_api_pack_handle(handles, data, offsetof(struct WMTTileRenderPipelineInfo, binary_archive_for_serialization), (id)info->binary_archive_for_serialization, @"MetalObject", NO);
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, num_binary_archives_for_lookup), &info->num_binary_archives_for_lookup, sizeof(info->num_binary_archives_for_lookup));
  memcpy((char *)data.mutableBytes+offsetof(struct WMTTileRenderPipelineInfo, fail_on_binary_archive_miss), &info->fail_on_binary_archive_miss, sizeof(info->fail_on_binary_archive_miss));
  NSMutableDictionary *payload = [@{@"data":data, @"handles":handles, @"root-offset":@(offsetof(struct unixcall_mtldevice_newrenderpso, info))} mutableCopy];
  if (info->num_binary_archives_for_lookup || info->binary_archive_for_serialization) {
    [payload release]; return wmt_trace_api_pack_failure(packet, @"binary archive consumer requires captured archive bytes; projection is not sufficient");
  }
  [packet[@"payloads"] addObject:payload]; [payload release];
  break;
}
